steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/delta-fact-410808/animcon:lates', '.'] 
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/delta-fact-410808/animcon:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'update-server'
    - '--image'
    - 'gcr.io/delta-fact-410808/animcon:latest'
    - '--region'
    - 'europe-north1'