serviceAccount: 'delta-fact-410808@appspot.gserviceaccount.com'

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/delta-fact-410808/gcp_test_app:lates', '.'] 
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/delta-fact-410808/gcp_test_app:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'update-server'
    - '--image'
    - 'gcr.io/delta-fact-410808/gcp_test_app:latest'
    - '--region'
    - 'europe-north1'
