program: animals10/train_model.py
method: grid
metric:
  goal: maximize
  name: test/accuracy
parameters:
  learning_rate:
    values: [0.001, 0.01, 0.1]
  batch_size:
    values: [16, 32, 64]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
